version: '3.5'

services:
  nifi:
    deploy:
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 1639M

volumes:
  nifi-conf-vol:
    name: ${NIFI_CONF_VOL_NAME:-nifi-conf-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  nifi-database-vol:
    name: ${NIFI_DATABASE_VOL_NAME:-nifi-database-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  nifi-flowfile-vol:
    name: ${NIFI_FLOWFILE_VOL_NAME:-nifi-flowfile-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  nifi-content-vol:
    name: ${NIFI_CONTENT_VOL_NAME:-nifi-content-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: 1
      ebstype: gp2

  nifi-provenance-vol:
    name: ${NIFI_PROVENANCE_VOL_NAME:-nifi-provenance-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: relocatable
      size: 2
      ebstype: gp2

  nifi-additional-libs-vol:
    name: ${NIFI_ADDITIONAL_LIBS_VOL_NAME:-nifi-additional-libs-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

  ingest-data-vol:
    name: ${INGEST_DATA_VOL_NAME:-ingest-data-vol}
    driver: 'cloudstor:aws'
    driver_opts:
      backing: shared

